const ACTION_TYPES = {
  LOGIN: 'LOGIN',
  LOGOUT: 'LOGOUT',
  SET_MENU: 'SET_MENU',
  SET_SUBMENU: 'SET_SUBMENU',
  SET_MEAL: 'SET_MEAL',
  SET_LOCATION: 'SET_LOCATION',
  SET_ADDRESS_INFO: 'SET_ADDRESS_INFO',

  ADD_TO_CART: 'ADD_TO_CART',
  UPDATE_ITEM_QUANTITY: 'UPDATE_ITEM_QUANTITY',
  DELETE_CARD_ITEM: 'DELETE_CARD_ITEM',
  CLEAR_CART: 'CLEAR_CART',

  SET_USER: 'SET_USER',
  SET_PAYROLL: 'SET_PAYROLL',
};

export default ACTION_TYPES;
